##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = translator

SRC = translator.cpp

LIBRARY=libtranslator.a

include ../../Makefile.local
