##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_bitvector

SRC = bitvector_theorem_producer.cpp theory_bitvector.cpp

HEADERS = \
 bitvector_proof_rules.h \
 bitvector_theorem_producer.h \
 bitvector_expr_value.h \
 bitvector_exception.h

LIBRARY=libtheory_bitvector.a

include ../../Makefile.local
