##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_records

SRC = theory_records.cpp records_theorem_producer.cpp

HEADERS = records_proof_rules.h records_theorem_producer.h

LIBRARY=libtheory_records.a

include ../../Makefile.local
