##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = vcl

SRC = vcl.cpp vc_cmd.cpp

LIBRARY=libvcl.a

include ../../Makefile.local
