##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_simulate

SRC = theory_simulate.cpp simulate_theorem_producer.cpp

HEADERS = simulate_proof_rules.h simulate_theorem_producer.h

LIBRARY=libtheory_simulate.a

include ../../Makefile.local
