##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_core

SRC = theory.cpp \
 theory_core.cpp \
 core_theorem_producer.cpp \
 expr_transform.cpp \
 bryant.cpp

HEADERS = core_proof_rules.h \
          core_theorem_producer.h

LIBRARY=libtheory_core.a

include ../../Makefile.local
