##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = util

SRC = debug.cpp \
  statistics.cpp \
  rational.cpp \
  rational-native.cpp \
  rational-gmp.cpp

LIBRARY = libcvc_util.a

EXTRAFLAGS = $(RATIONAL_FLAGS)

include ../../Makefile.local
