##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theorem

SRC = assumptions.cpp \
  theorem.cpp theorem_manager.cpp theorem_producer.cpp common_theorem_producer.cpp

HEADERS = theorem_value.h common_theorem_producer.h

LIBRARY=libtheorem.a

include ../../Makefile.local
