##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_uf

SRC = uf_theorem_producer.cpp theory_uf.cpp

HEADERS = \
	uf_proof_rules.h \
	uf_theorem_producer.h

LIBRARY=libtheory_uf.a

include ../../Makefile.local
