##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_array

SRC = array_theorem_producer.cpp theory_array.cpp

HEADERS = array_proof_rules.h array_theorem_producer.h

LIBRARY=libtheory_array.a

include ../../Makefile.local
