##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_datatype

SRC = datatype_theorem_producer.cpp theory_datatype.cpp theory_datatype_lazy.cpp

HEADERS = datatype_proof_rules.h \
	datatype_theorem_producer.h

LIBRARY=libtheory_datatype.a

include ../../Makefile.local
