##################################################
# About this Makefile
#
# This Makefile depends on Makefile.opts
##################################################

MODULE = theory_quant

SRC = theory_quant.cpp quant_theorem_producer.cpp

HEADERS = quant_proof_rules.h quant_theorem_producer.h

LIBRARY=libtheory_quant.a

include ../../Makefile.local
